### ISSUE TITLE
Formatting Issue with Statblock (Two Column)

### ISSUE THREAD

**Issue by austinpire** [Tetra-cube/Tetra-cube.github.io#10]
I've noticed that when adding abilities with the two-column format, the statblock will only add one ability to the left side, and all the rest come to the right side. This is annoying because it does not matter how much empty space is on the left side, the right side will always fill up with abilities.
This happens when I create a monster.

![Error with Priest](https://user-images.githubusercontent.com/63560673/79078591-f6909880-7cce-11ea-9994-e5cffb145067.png)

**Comment by Tetra-cube** [comment]
Use the little << and >> buttons next to Update Statblock to fix this
