### ISSUE TITLE
Custom CR prevents markdown generation

### ISSUE THREAD

**Issue by fderudder** [Tetra-cube/Tetra-cube.github.io#14]
Setting a Custom Challenge Rating for a statblock prevents the markdown generation to work correctly. All other generation seem to work fine (print, image, save & load).

Repro steps:
- Create any statblock (default works)
- set Challenge Rating to Custom CR
- hit the "View Markdown" button
- new tab opens on about:blank

tested in FF 81.0 (64 bits) & Edge 85.0 (chromium, 64 bits)

**Comment by Kargoneth** [comment]
I will augment the comments of @fderudder:
> The content of the new tab appears to be correct, but the loading bar continues to spin (as though the page still has more to do).
> Rather than "about:blank", the URL of the new tab should probably share the same name prefix as the files generated by the "Save" button

**Comment by Tetra-cube** [comment]
Fixed this a while back and forgot to close it
