### ISSUE TITLE
Feature request: A little more control over alignment

### ISSUE THREAD

**Issue by ajfclark** [Tetra-cube/Tetra-cube.github.io#16]
In the life section, it would be super useful if there were a couple of drop down boxes for alignment so each of the axis could be locked independently.

e.g. [Random] [Good] or [Chaotic] [Random] or [Lawful] [ Good]

**Comment by Kargoneth** [comment]
> In the life section, it would be super useful if there were a couple of drop down boxes for alignment so each of the axis could be locked independently.
> 
> e.g. [Random] [Good] or [Chaotic] [Random] or [Lawful] [ Good]

There is no "life section". Are you sure that you are commenting on the correct project?

**Comment by ajfclark** [comment]
Sorry, in the character generator, around dnd/dnd-char-gen.html:292.

**Comment by ajfclark** [comment]
Though looking at how it generates, there's no link between the alignment and the rest is there?
https://github.com/Tetra-cube/Tetra-cube.github.io/blob/c6a4d4fd2a1b5206224703c7c04cadecfec8d525/dnd/js/char-gen-script.js#L835

So it could either be handled separately or I could just ignore what the generator comes up with.

**Comment by Tetra-cube** [comment]
Yeah, the life section is made with the expectation that you'll ignore whatever parts you don't like
