### ISSUE TITLE
Statblock Generator: Feature Proposal: Add an optional text field for a Shortened Plural Name and a corresponding new Formatting keyword "[MONS]"

### ISSUE THREAD

**Issue by Kargoneth** [Tetra-cube/Tetra-cube.github.io#19]
The shortened names field is quite useful, but several times I've run across the fact that the English language has several ways of pluralization. If you look at the canon Ochre Jelly, you can see that the plural of "jelly" is not "jellys", but is "jellies". This is not normally a problem for most creatures ("[MON]s" usually suffices), but in this case, it generates an incorrect result. This would also allow one to account for words like "deer", where the plural is the same word.

I would request the following additions:
- A new text field below the Shortened Name field called Shortened Plural Name (or something similar)
- A new formatting keyword, "[MONS]", to represent the value of the Shortened Plural Name field and the "[MON]" keyword
  - If the Shortened Plural Name field is empty, it uses the value of the Shortened Name field (and functions equivalently to the "[MON]" keyword)
  - If the Shortened Name field is also empty, it can use the value of the Name field (much the same as the Shortened Name field does)

I've attached a zip file of a nearly-fully-formatted Ochre Jelly ".monster" file where the plural of "jelly" has been left unformatted.
[ochre jelly.zip](https://github.com/Tetra-cube/Tetra-cube.github.io/files/5945347/ochre.jelly.zip)

**Comment by Tetra-cube** [comment]
Added

**Comment by Kargoneth** [comment]
Awesome! Thank you very much!
