### ISSUE TITLE
License for changing and using Tetra-cube

### ISSUE THREAD

**Issue by Kelfecil** [Tetra-cube/Tetra-cube.github.io#29]
Hello!

I just wanted to ask if it would be possible for someone to take tetra-cube and change some of the parameters so that it exports a slightly different kind of file. I want to specifically make it export stat block images without certain elements in them, such as skills and sense as well as the entire attributes line.

Thank you for your time and for the amazing tool you have made.

Cheers,
~Kelf

**Comment by Tetra-cube** [comment]
Sure
