### ISSUE TITLE
Skeleton Preset Issue

### ISSUE THREAD

**Issue by RecursiveStar** [Tetra-cube/Tetra-cube.github.io#5]
Your skeleton preset is missing the condition immunity for exhaustion and the damage immunity for poison.

Great tool you have here, though :)

EDIT: Ghoul statblock is missing the damage immunity for poison as well as its immunities to the charmed and exhaustion conditions as well.

**Comment by daft-develop** [comment]
I looked at the code and it appears the stats are pulled from api.open5e.com. I've confirmed on open5e's end the same values are missing, so I've generated a pull request on that project to add the missing values for both creatures. If the PR gets accepted, it should automatically get picked up on Tetra-cube on a page reload.

API call for Skeleton: https://api.open5e.com/monsters/?name=Skeleton
API call for Ghoul: https://api.open5e.com/monsters/?name=Ghoul

PR on Open5e: https://github.com/eepMoody/open5e-api/pull/48

**Comment by RecursiveStar** [comment]
@daft-develop Your pull request was merged but the values do not seem to be updated, either on the API's end or your end.

![958c3624eacbff6aa70b5ec06f78f00b](https://user-images.githubusercontent.com/38794241/80179362-60157e80-85ce-11ea-81ac-68edc0e2622b.png)
![0990183ed3d484c1029bc2ccce2dcf26](https://user-images.githubusercontent.com/38794241/80179364-60157e80-85ce-11ea-9905-8b9f05c158ee.png)

**Comment by daft-develop** [comment]
@RecursiveStar I created a local build of Open5e with the latest master commit on my machine and the changes have been incorporated and show up as expected on both the local open5e and a local Tetra build pointing to my local open5e.

It looks like the public hosted version of Open5e hasn't been updated to match the latest commits. Both my changes and few others in the Open5e commit history don't show up on the public page. I suspect even though the changes have been pulled in to master, Open5e hasn't updated the public build for whatever reason, possibly queuing up some other changes? You could follow up directly with the open5e project to see if they have a scheduled release or open an issue, perhaps the database just wasn't refreshed.

**Comment by Tetra-cube** [comment]
Open5e issue
