### ISSUE TITLE
Suggestions: Lair Actions, Regional Effects, New Presets

### ISSUE THREAD

**Issue by Abelhawk** [Tetra-cube/Tetra-cube.github.io#7]
I absolutely love this resource and use it all the time. I especially like how it displays the creature data in a near identical way that the official D&D books do. I was wondering whether the following will ever be implemented:

- **Lair Actions?** Will there ever be a way to display Lair Actions somewhere on the statblock, or even just separately but in the same format as the rest of the text?
- **Regional Effects?**
- **New Source Presets?** I notice that the Character Generator can pull data from many other D&D resources, but the Statblock Generator seems limited in the presets it can use. Is this a licensing/copyright issue, or would it be possible to implement new presets and action presets from other resources?
- **Race Presets?** The action preset block is very useful for using existing monster abilities, but I notice it's lacking racial abilities from the races in the Player's Handbook. Could these be implemented eventually to make it easier to add a race to an NPC statblock? (i.e., Relentless Endurance for a half-orc thug)

**Comment by Tetra-cube** [comment]
Source presets is indeed a licensing/copyright issue. The others have been added!
